version: "3.5"
services:
  postgres:
    image: postgres:16
    container_name: postgres_portal
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5444:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
